title: Kachra Patti
author: kaustubhdeokar
email: kaustubhd9@gmail.com
theme: minima
description: > Software Developer khachra patti. Rough work yaad rahe isiliye banaya yeh. Kuch bhi likhunga , kya kar loge.
              <br> Itna fad code likhunga, oracle docs isse update hogi, dekh lena. Baki ab toh bas karta hu, jaldi milte hain.
# social links
github_username:  kaustubhdeokar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
