title: Refactoring...
author: kaustubhdeokar
email: kaustubhd9@gmail.com
theme: minima
description: Learning new & improving on the familiar. 
# social links
github_username:  kaustubhdeokar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
